/*
 * PassPortDatabaseConnection.h
 *
 *  Created on: 2016年3月10日
 *      Author: shenwei
 */

#ifndef SRC_DB_PASSPORTDATABASECONNECTION_H_
#define SRC_DB_PASSPORTDATABASECONNECTION_H_

#include "db/MySQLConnection.h"
#include "db/DatabaseWorkerPool.h"

class PassPortDatabaseConnection : public MySQLConnection
{
public:
	//- Constructors for sync and async connections
	PassPortDatabaseConnection(MySQLConnectionInfo& connInfo) :
			MySQLConnection(connInfo) {
	}

	//- Loads database type specific prepared statements
	void DoPrepareStatements() override;
};

typedef DatabaseWorkerPool<PassPortDatabaseConnection> PassPortDatabaseWorkerPool;

enum PassPortDatabaseStatements
{
	//test
	ASY_TEST,
	//baseinfo
	UP_BASEINFO_BASEINFO,
	UP_BASEINFO_HERO,
	UP_BASEINFO_REGISTRATION,
	UP_BASEINFO_LOTTERY,
	UP_BASEINFO_COUPON,

	SEL_BASEINFO,
	INSERT_BASEINFO,
	//UP_BASEINFO_BASEINFO,



	UP_BASEINFO_ALL,
	UP_INTRUSION,
	UP_LEVELPASSREWARD,
	UP_TIMESTAMP,
	UP_ADDMONEY,
	UP_ADDDIAMOND,
	UP_CLIP,
	OPEN_HERO,

	UP_LOGIN,
	UP_BASEINFO_INTRUSION,



	//baseinfo_forceguide
	SEL_BASEINFOFORCEGUIDE,
	INSERT_BASEINFOFORCEGUIDE,
	UP_BASEINFOFORCEGUIDE,
	//hero
	SEL_BASEINFOHERO,
	INSERT_BASEINFOHERO,
	UP_UPGRADEHERO,
	UP_HEROSTATUS,
	FIND_HEROID,

	//hero_runes关系表
	SEL_HERORUNES,
	INSERT_HERORUNES,
	UP_RUNESTATUS,
	//Item
	SEL_BASEINFOITEMSTORE,
	INSERT_BASEINFOITEMSTORE,
	UP_BASEINFOITEMSTORE,
	//Levels
	SEL_BASEINFOLEVELS,
	INSERT_BASEINFOLEVELS,
	UP_BASEINFOLEVELS,

	//LevelGroup
	SEL_BASEINFOLEVELGROUPS,
	INSERT_BASEINFOLEVELGROUPS,
	UP_BASEINFOLEVELGROUPS,

	SEL_LEVELGROUPSLEVELS,
	INSERT_LEVELGROUPS_LEVELS,
	UP_LEVELGROUPSLEVELS,



	//mines
	SEL_BASEINFOMINES,
	INSERT_BASEINFOMINES,
	UP_BASEINFOMINES,

	//missions
	SEL_BASEINFOMISSION,
	INSERT_BASEINFOMISSION,
	UP_BASEINFOMISSION,
	//monstermap
	SEL_BASEINFOMONSTERMAP,
	INSERT_BASEINFOMONSTERMAP,
	UP_BASEINFOMONSTERMAP,
	//
	SEL_BASEINFPLATFORMSTORE,
	INSERT_BASEINFPLATFORMSTORE,
	UP_BASEINFPLATFORMSTORE,
	//
	SEL_BASEINFOTECHUPGRADE,
	UP_BASEINFOTECHUPGRADE,
	INSERT_BASEINFOTECHUPGRADE,

	//查询指定towerclassindex和towerinclassindex的tower 值
	SEL_BASEINFOTOWERUPGRADE,
	INSERT_BASEINFOTOWERUPGRADE,
	UP_BASEINFOTOWERUPGRADE,
	//Log
	INSERT_NETLOG,






	MAX_PASSPORTDATABASE_STATEMENTS,

};

#endif /* SRC_DB_PASSPORTDATABASECONNECTION_H_ */
