// generated by pktcoder.
struct UserId {
    u64 low;
    u64 high;
    void _save(Variable_object &_vobj) const {
        PacketDataHelper<u64>::save(_vobj, "low", low);
        PacketDataHelper<u64>::save(_vobj, "high", high);
    }
    void _load(Variable_object &_vobj) {
        PacketDataHelper<u64>::load(_vobj, "low", low);
        PacketDataHelper<u64>::load(_vobj, "high", high);
    }
};
inline DataStream & operator <<(DataStream &s, const UserId &v) {
    s << v.low;
    s << v.high;
    return s;
}
inline DataStream & operator >>(DataStream &s, UserId &v) {
    s >> v.low;
    s >> v.high;
    return s;
}
struct IndexAndCount {
    unsigned int index;
    unsigned int count;
    void _save(Variable_object &_vobj) const {
        PacketDataHelper<unsigned int>::save(_vobj, "index", index);
        PacketDataHelper<unsigned int>::save(_vobj, "count", count);
    }
    void _load(Variable_object &_vobj) {
        PacketDataHelper<unsigned int>::load(_vobj, "index", index);
        PacketDataHelper<unsigned int>::load(_vobj, "count", count);
    }
};
inline DataStream & operator <<(DataStream &s, const IndexAndCount &v) {
    s << DataStream::ccu(v.index);
    s << DataStream::ccu(v.count);
    return s;
}
inline DataStream & operator >>(DataStream &s, IndexAndCount &v) {
    s >> DataStream::cu(v.index);
    s >> DataStream::cu(v.count);
    return s;
}
